wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.14
    framework: huggingface
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1650203636
    t:
      1:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      2:
      - 1
      - 5
      - 11
      - 49
      - 53
      - 55
      3:
      - 1
      - 13
      4: 3.9.7
      5: 0.12.14
      6: 4.17.0
      8:
      - 5
batch_size:
  desc: null
  value: 8
data_path:
  desc: null
  value: /home/seonggye/Syllogism-1/datasets/
eval_batch_size:
  desc: null
  value: 32
eval_interval:
  desc: null
  value: 2000
learning_rate:
  desc: null
  value: 1.0e-05
log_interval:
  desc: null
  value: 100
max_len:
  desc: null
  value: 512
model_path:
  desc: null
  value: ./model_log/
num_epochs:
  desc: null
  value: 10
num_iteration:
  desc: null
  value: 1000
save_interval:
  desc: null
  value: 1000
seed:
  desc: null
  value: 1234
